### ISSUE TITLE
TODO 20160112

### ISSUE THREAD

**Issue by Manicarus** [Manicarus/BJCloud#3]
- [x] 각자 원격 저장소를 만드는 방법 교육하기
- [x] 깃허브 클라이언트를 다루는 방법 교육하기
- [x] 동아리실 할당된 IP 주소 공지하기
- [ ] 라이센스 정하기
- [x] 멘토링 활동 자료와 회의록을 깃허브에 올리도록 하기
